import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/layout'

export default function Home() {
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>BuJo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          BuJo
        </h1>

        <h2>
          <Link href="/future-log"><a>Future Log</a></Link>
        </h2>

        <h2>
          <Link href="/month"><a>Month</a></Link>
        </h2>

        <h2>
          <Link href="/week"><a>Week</a></Link>
        </h2>

        <h2>
          <Link href="/day"><a>Day</a></Link>
        </h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </Layout>

  )
}
